grades=[[5,3,3,5,4],[2,2,2,3],[4,5,5,2],[4,4,3],[5,5,5,4,5]]
students={'Johnny','Bilbo','Steve','Kendrik','Aaron'}
average_mark={}
students=sorted(students)
a=grades.pop(0)
a1=sum(a)/len(a)
a2=students[0]
average_mark.update({a2:a1})
b=grades.pop(0)
b1=sum(b)/len(b)
b2=students[1]
average_mark.update({b2:b1})
c=grades.pop(0)
c1=sum(c)/len(c)
c2=students[2]
average_mark.update({c2:c1})
d=grades.pop(0)
d1=sum(d)/len(d)
d2=students[3]
average_mark.update({d2:d1})
e=grades.pop(0)
e1=sum(e)/len(e)
e2=students[4]
average_mark.update({e2:e1})
print(average_mark)